# Module 8 - Recommendation Examples

Side-by-side top-5 recommendations for three example users, one per method, so the qualitative differences between algorithms are visible. The table is generated by `scripts/recommendation_examples.py` (single source of truth, also used by the report).

In [1]:
%run ../scripts/recommendation_examples.py

User 2 - listens to: Duran Duran; Morcheeba; Air
  Popularity (listeners) -> Britney Spears; Katy Perry; The Beatles; Rihanna; Avril Lavigne
  Item-item CF           -> Pet Shop Boys; Orchestral Manoeuvres in the Dark; The Human League; Simple Minds; Ultravox
  Content-based          -> Pet Shop Boys; Eurythmics; Moby; Soft Cell; Freur
  ALS (MF)               -> The Prodigy; Pet Shop Boys; Moby; Robbie Williams; Simple Minds
  Social (friends)       -> Pet Shop Boys; Erasure; U2; Thompson Twins; The Cure

User 3 - listens to: Pleq; Segue; Max Richter
  Popularity (listeners) -> Lady Gaga; Britney Spears; Katy Perry; The Beatles; Rihanna
  Item-item CF           -> ksandr; Noto; ksandr and I.M.M.U.R.E.; Alva Noto + Ryuichi Sakamoto with Ensemble Modern; Arbre Noir
  Content-based          -> Aphex Twin; #11715; Biosphere; Helios; The Future Sound of London
  ALS (MF)               -> The Cranberries; 30 Seconds to Mars; Muse; Janelle Monáe; Pearl Jam
  Social (friends)       -> Aphex Twin; Venetian Snares; Sigur Rós; Apparat; Björk

User 4 - listens to: Depeche Mode; Porcupine Tree; De/Vision
  Popularity (listeners) -> Lady Gaga; Britney Spears; Katy Perry; The Beatles; Rihanna
  Item-item CF           -> Coldplay; Pet Shop Boys; The Beatles; Muse; New Order
  Content-based          -> Muse; The Connells; R.E.M.; Coldplay; No Doubt
  ALS (MF)               -> Muse; Coldplay; 30 Seconds to Mars; Snow Patrol; Hurts
  Social (friends)       -> Dave Gahan; Martin L. Gore; Coldplay; Recoil; And One

Wrote /Users/paugratacosfuste/Desktop/ESADE/term 3/Recommender Systems/Individual Assignment/docs/recommendation_examples.csv

In [2]:
import pandas as pd
from recsys.config import PROCESSED_DIR
ex = pd.read_csv(PROCESSED_DIR.parents[1] / 'docs' / 'recommendation_examples.csv')
for uid in ex['user_id'].unique():
    sub = ex[ex['user_id'] == uid]
    print(f"\nUser {uid} listens to: {sub['user_taste'].iloc[0]}")
    display(sub[['method','recommendations']].set_index('method'))

User 2 listens to: Duran Duran; Morcheeba; Air

                                                          recommendations
method
Popularity (listeners)  Britney Spears; Katy Perry; The Beatles; Rihan...
Item-item CF            Pet Shop Boys; Orchestral Manoeuvres in the Da...
Content-based           Pet Shop Boys; Eurythmics; Moby; Soft Cell; Freur
ALS (MF)                The Prodigy; Pet Shop Boys; Moby; Robbie Willi...
Social (friends)        Pet Shop Boys; Erasure; U2; Thompson Twins; Th...

User 3 listens to: Pleq; Segue; Max Richter

                                                          recommendations
method
Popularity (listeners)  Lady Gaga; Britney Spears; Katy Perry; The Bea...
Item-item CF            ksandr; Noto; ksandr and I.M.M.U.R.E.; Alva No...
Content-based           Aphex Twin; #11715; Biosphere; Helios; The Fut...
ALS (MF)                The Cranberries; 30 Seconds to Mars; Muse; Jan...
Social (friends)        Aphex Twin; Venetian Snares; Sigur Rós; Appara...

User 4 listens to: Depeche Mode; Porcupine Tree; De/Vision

                                                          recommendations
method
Popularity (listeners)  Lady Gaga; Britney Spears; Katy Perry; The Bea...
Item-item CF            Coldplay; Pet Shop Boys; The Beatles; Muse; Ne...
Content-based              Muse; The Connells; R.E.M.; Coldplay; No Doubt
ALS (MF)                Muse; Coldplay; 30 Seconds to Mars; Snow Patro...
Social (friends)        Dave Gahan; Martin L. Gore; Coldplay; Recoil; ...

## What the examples show

- **Popularity is taste-blind.** It serves the same mainstream pop (Britney Spears, Katy Perry, Lady Gaga) to every user - including an ambient / modern-classical listener, where it is wildly off. This is the popularity-bias problem made concrete.
- **The personalised methods align with the user's genre.** For the 80s-synthpop user they converge on Pet Shop Boys, OMD, Eurythmics, Erasure; for the ambient user on Aphex Twin, Biosphere, Alva Noto.
- **Methods differ in character.** Item-item CF stays closest to the user's exact niche (even obscure artists); content-based pulls tag-similar artists; social surfaces what friends play (e.g. Depeche Mode's own members for a Depeche Mode fan); ALS generalises and can drift toward the mainstream for very niche tastes.
- This is the qualitative counterpart to the quantitative comparison in notebook 02.